name: Docker

on:
  push:

jobs:
  build-and-publish-head:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.1.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: arrai
        image-tag: ${{ github.sha }}